<?php

namespace AppBundle\Repository;

/**
 * JoiningRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JoiningRepository extends \Doctrine\ORM\EntityRepository
{
}
