_index:
    path:  /
    defaults: { _controller: AppBundle:Joining:index }

app:
    resource: '@AppBundle/Controller/'
    type: annotation

# Lexik Paybox Bundle
lexik_paybox:
    resource: '@LexikPayboxBundle/Resources/config/routing.yml'
